[package]
name = "aoc2024"
version = "0.1.0"
edition = "2021"

[dependencies]
aoc = { git = "https://github.com/evenfurther/aoc" }
bytecount = "0.6.8"
eyre = "0.6.12"
regex= "*"
[build-dependencies]
aoc-build = { git = "https://github.com/evenfurther/aoc" }